-- AlterTable
ALTER TABLE "BodyMetric" ADD COLUMN     "armCm" DOUBLE PRECISION,
ADD COLUMN     "chestCm" DOUBLE PRECISION,
ADD COLUMN     "leanMassKg" DOUBLE PRECISION,
ADD COLUMN     "thighCm" DOUBLE PRECISION,
ADD COLUMN     "waistCm" DOUBLE PRECISION;
